### ISSUE TITLE
Redis Server Error

### ISSUE THREAD

**Issue by lilRufi** [howardchung/watchparty#176]
```
ReplyError: ERR syntax error
    at parseError (C:\Users\Rauf\watchparty\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (C:\Users\Rauf\watchparty\node_modules\redis-parser\lib\parser.js:302:14) {
  command: {
    name: 'set',
    args: [
      '/married-goose-direct',
      '{"video":"","videoTS":0,"subtitle":"","paused":false,"chat":[],"nameMap":{},"pictureMap":{},"creationTime":"2021-04-02T10:04:41.534Z"}',        
      'KEEPTTL'
    ]
  }
}

```

I'm getting this error.

**Comment by howardchung** [comment]
I think this is a new feature that requires Redis 6+
