### ISSUE TITLE
error: relation "room" does not exist + another error

### ISSUE THREAD

**Issue by dillfrescott** [howardchung/watchparty#613]
I am getting this error when attempting to start the server. It results in it not listening on port 8080:

```
error: relation "room" does not exist
    at Parser.parseErrorMessage (/watchparty/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/watchparty/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/watchparty/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/watchparty/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[ERROR] 23:37:49 error: relation "room" does not exist
```

**Comment by dillfrescott** [comment]
I removed the database line from `.env` and now its saying:

```
Error: ENOENT: no such file or directory, open
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at Object.<anonymous> (/watchparty/server/server.ts:40:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/watchparty/node_modules/source-map-support/source-map-support.js:547:25)
    at Module.m._compile (/tmp/ts-node-dev-hook-48419174208956384.js:69:33)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-48419174208956384.js:114:20)
    at require.extensions.<computed> (/tmp/ts-node-dev-hook-48419174208956384.js:71:20)
    at Object.nodeDevHook [as .ts] (/watchparty/node_modules/ts-node-dev/lib/hook.js:63:13)
[ERROR] 00:52:10 Error: ENOENT: no such file or directory, open
```

**Comment by howardchung** [comment]
It looks like this is failing because you have HTTPS enabled but no config for an SSL cert

**Comment by dillfrescott** [comment]
Oh okay. Thank you!

**Comment by dillfrescott** [comment]
@howardchung Still happening, I made sure SSL was disabled as I am using a local database. Please help.

**Comment by scheissegalo** [comment]
> It looks like this is failing because you have HTTPS enabled but no config for an SSL cert

Can you explain this a little deeper please? I have the same issue. I use Nginx as reverse proxy for whatchparty but that has nothing to do with node or does it? Nginx is set for https, but node is hosting on port 8088 so no https enabled here. Or am I totally wrong? 
Or do you mean postgres ssl enabled? My postgres ssl is disabled. I even downloadet the postgres docker from the line 73 in your https://github.com/howardchung/watchparty/blob/master/dev/watchparty.sh but still gives me the same error.
