### ISSUE TITLE
Redis connection error

### ISSUE THREAD

**Issue by dillfrescott** [howardchung/watchparty#837]
```
Error: Connection is closed.
    at close (/root/watchparty/node_modules/ioredis/built/redis/event_handler.js:189:25)
    at Socket.<anonymous> (/root/watchparty/node_modules/ioredis/built/redis/event_handler.js:156:20)
    at Object.onceWrapper (node:events:628:26)
    at Socket.emit (node:events:525:35)
    at TCP.<anonymous> (node:net:301:12)
```
This is thrown by the server when attempting to launch a virtual browser. :( Redis is set up and running on the right port too.

**Comment by howardchung** [comment]
This seems more like a configuration issue. . . what is your REDIS_URL config value? Is Redis definitely listening to 0.0.0.0 and/or running in a container?

**Comment by dillfrescott** [comment]
Ah yes, sorry to bother, you were right. It was a config issue!
